publish_to: none
name: miniaudio_dart_web
description: Web implementation of the MiniaudioDart package.
version: 1.0.0
repository: https://github.com/DaniilAlpha/miniaudio_dart/tree/master/miniaudio_dart_web

#####

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  js: ^0.6.3
  miniaudio_dart_platform_interface:
    path: ../miniaudio_dart_platform_interface

dev_dependencies:
  flutter_lints: ^3.0.1

#####

flutter:
  plugin:
    implements: miniaudio_dart
    platforms:
      web:
        pluginClass: MiniaudioDartWeb
        fileName: miniaudio_dart_web.dart

  assets:
    - packages/miniaudio_dart_web/build/miniaudio_dart_web.loader.js
    - packages/miniaudio_dart_web/build/miniaudio_dart_web.wasm
    - packages/miniaudio_dart_web/build/miniaudio_dart_web.js
    - packages/miniaudio_dart_web/build/miniaudio_dart_web.aw.js
    - packages/miniaudio_dart_web/build/miniaudio_dart_web.ww.js