publish_to: none
name: miniaudio_dart_platform_interface
description: A common platform interface for the MiniaudioDart package.
version: 1.0.0
repository: https://github.com/DaniilAlpha/miniaudio_dart/tree/master/miniaudio_dart_platform_interface

#####

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_lints: ^2.0.1
